### PR TITLE
fix (q chat): ensure generated files end with newline character, and no trailing whitespaces

### LINKED ISSUE #768: Amazon Q CLI doesn't add final newline character when creating or modifying files
**Issue Description:**
When using Amazon Q CLI to create or modify files, it doesn't add a final newline character at the end of files. This goes against 
standard development practices and can cause issues with various tools.

**Expected Behavior:**
Files created or modified by Amazon Q CLI should end with a newline character, following the POSIX standard and common development best 
practices.

**Current Behavior:**
Files are created or modified without a final newline character, which can cause:
• Git showing "\ No newline at end of file" in diffs
• Issues with some command-line tools that expect POSIX-compliant text files
• Linting and Checkstyle errors in projects that enforce this standard
• Problems when appending to these files programmatically

**Steps to Reproduce:**
1. Use Amazon Q CLI to create a new file or modify an existing one
2. Check if the file ends with a newline character
3. Observe that the final newline is missing

Environment:
• OS: macOS
• Amazon Q CLI version: 1.7.0

### PR DESCRIPTION
**Pull request by hsbakshi**
Fixes #768

This commit adds functionality to ensure all files created or modified by the fs_write tool end with a newline character, following Unix text file conventions. The change:

- Adds newline handling to create, str_replace, and insert operations
- Updates test cases to verify the new behavior
- Maintains backward compatibility with existing functionality
- Avoids common Checkstyle and Lint failures due to missing new line or trailing whitespace at the end of a line.

This improves compatibility with other tools and follows standard text file best practices.

*Issue #, if available:*
#768

*Description of changes:*

This PR addresses issue #768 by ensuring that all files created or modified by the fs_write tool end with a newline character, following Unix text file conventions.

* Added newline handling to all fs_write operations in Q CLI:
  * create command now ensures the file content ends with a newline
  * str_replace command preserves the trailing newline during replacements
  * insert command maintains the trailing newline after insertions
* Updated test cases to verify the new behavior
* Maintained backward compatibility with existing functionality

### Testing

I've verified this change by:
• Running the existing test suite which now checks for trailing newlines
• Manually testing with local Java and Python files to ensure proper newline handling
• Confirming that files created through the CLI properly end with newlines when viewed in various editors

### Why this matters

Many Unix tools expect text files to end with a newline character. Without a trailing newline, some tools might:
• Display warnings
• Concatenate files incorrectly
• Have issues with diffs and patches

This change improves compatibility with standard Unix tools and follows best practices for text file handling.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: crates/q_cli/src/cli/chat/tools/fs_write.rs [hunk 1]
```diff
@@ -87,6 +93,12 @@ impl FsWrite {
                     0 => Err(eyre!("no occurrences of \"{old_str}\" were found")),
                     1 => {
                         let file = file.replacen(old_str, new_str, 1);
+                        // Ensure file ends with a newline if it doesn't already
+                        let file = if !file.ends_with('\n') {
+                            format!("{}\n", file)
```
Comment (jsamuel1) [inline crates/q_cli/src/cli/chat/tools/fs_write.rs:98]: would file::push('\n') be more efficient for large strings?

**Comment by jsamuel1** [comment]
How are binary files handled?  Is create always text files?

File: crates/q_cli/src/cli/chat/tools/fs_write.rs (hunk 1 above)
Comment (hsbakshi) [reply crates/q_cli/src/cli/chat/tools/fs_write.rs:98]: Yes, good call! I will update this.

**Comment by hsbakshi** [comment]
> How are binary files handled? Is create always text files?

Yes, it only support text files and the variable for content is of type String.

**Comment by csantanapr** [comment]
This is a critical enhancement to add as soon as possible a lot of use cases depend on this. 
I also love the feature of trim trailing whitespace 👍

**Comment by brandonskiser** [comment]
Thanks for the contribution! Looks like a test is failing, should be an easy fix - asserting a [newline character at the end of the file](https://github.com/aws/amazon-q-developer-cli/blob/main/crates/q_cli/src/cli/chat/mod.rs#L1143)

You can also verify locally with `cargo test`

**Review by brandonskiser — APPROVED** [review]
